# Generated by Django 3.2.24 on 2024-06-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0036_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
